Repository LD4P/sinopia_editor, pull requests merged in 2019-08, with the labels that each got.

#1124 Fix InputURI so it can handle items modeled as an Object
  __tests__/components/editor/property/InputURI.test.js
  src/components/editor/property/InputURI.jsx
Labels: BFF

#1118 Add literal onBlur
  __tests__/components/editor/property/InputLiteral.test.js
  src/components/editor/ResourceTemplateForm.jsx
  src/components/editor/property/InputLiteral.jsx
Labels: BFF

#1128 Remove unnecessary click handlers and id property
  __tests__/components/editor/property/InputLiteral.test.js
  __tests__/components/editor/property/InputURI.test.js
  __tests__/components/editor/property/PropertyComponent.test.js
  src/components/editor/ResourceTemplateForm.jsx
  src/components/editor/property/InputLiteral.jsx
  src/components/editor/property/InputURI.jsx
  src/components/editor/property/PropertyComponent.jsx
Labels: BFF

#1116 [Refactor] extract Literal from InputLiteral
  __tests__/actions/index.test.js
  __tests__/components/editor/property/InputLiteral.test.js
  __tests__/components/editor/property/InputURI.test.js
  __tests__/components/editor/property/InputValue.test.jsx
  __tests__/reducers/inputs.test.js
  src/actions/index.js
  src/components/editor/property/InputLiteral.jsx
  src/components/editor/property/InputURI.jsx
  src/components/editor/property/InputValue.jsx
  src/reducers/inputs.js
Labels: BFF

#1131 Bootstrap styles don't allow for labels that wrap the input
  src/components/editor/property/InputURI.jsx
Labels: BFF

#1132 The exist method does not take a second argument
  __tests__/components/editor/property/InputLiteral.test.js
  __tests__/components/editor/property/InputURI.test.js
  src/components/editor/property/InputLiteral.jsx
  src/components/editor/property/InputURI.jsx
Labels: BFF

#1135 Tagged Release 0.3.9
  .github/ISSUE_TEMPLATE/tagged-release.md
  README.md
  package-lock.json
  package.json
Labels: BFF, M4

#1139 Fixes InputLookupSinopia to handle items as object rather than array.
  src/components/editor/property/InputLookupSinopia.jsx
Labels: BFF

#1123 [Refactor] GroupChoiceModal uses thunk for saving to trellis
  __tests__/actionCreators/resources.test.js
  __tests__/components/editor/GroupChoiceModal.test.js
  __tests__/reducers/index.test.js
  src/actionCreators/resources.js
  src/actions/index.js
  src/components/editor/GroupChoiceModal.jsx
  src/reducers/index.js
Labels: BFF, M4

#1141 Payload is always present and always a string
  __tests__/reducers/index.test.js
  src/reducers/index.js
Labels: BFF, bug

#1143 Create default labels in the ResourceStateBuilder
  __tests__/ResourceStateBuilder.test.js
  __tests__/actionCreators/resources.test.js
  src/ResourceStateBuilder.js
  src/components/editor/property/InputListLOC.jsx
  src/components/editor/property/InputLookupQA.jsx
  src/components/editor/property/InputLookupSinopia.jsx
  src/selectors/resourceSelectors.js
Labels: BFF

#1133 Make InputLiteral a functional component
  __tests__/components/editor/property/InputLiteral.test.js
  src/components/editor/property/InputLiteral.jsx
Labels: BFF

#1137 Fixes typehead bug when hitting backspace key.
  __tests__/integration/previewRDFHelper.js
  src/components/editor/property/InputListLOC.jsx
  src/components/editor/property/InputLookupQA.jsx
  src/components/editor/property/InputLookupSinopia.jsx
Labels: BFF

#1140 set loc genre subauths to active/deprecated
  static/lookupConfig.json
Labels: Authorities

#1129 Prop component refactor
  .babelrc
  __tests__/Utilities.test.js
  __tests__/components/App.test.js
  __tests__/components/editor/ResourceTemplateForm.test.js
  __tests__/components/editor/property/PropertyComponent.test.js
  __tests__/utilities/propertyTemplates.test.js
  package-lock.json
  package.json
  src/Utilities.js
  src/actionCreators/resources.js
  src/components/editor/property/InputListLOC.jsx
  src/components/editor/property/InputLiteral.jsx
  src/components/editor/property/InputLookupQA.jsx
  src/components/editor/property/InputLookupSinopia.jsx
  src/components/editor/property/InputURI.jsx
  src/components/editor/property/PropertyComponent.jsx
  src/components/editor/property/PropertyTemplateOutline.jsx
  src/utilities/propertyTemplates.js
Labels: BFF, M4, editor-refactor

#1150 Components do not need to know about the internals of state
  __tests__/ResourceValidator.test.js
  __tests__/reducers/inputs.test.js
  __tests__/selectors/resourceSelectors.test.js
  src/ResourceValidator.js
  src/components/editor/ErrorMessages.jsx
  src/components/editor/ResourceTemplateForm.jsx
  src/components/editor/property/InputLang.jsx
  src/components/editor/property/InputListLOC.jsx
  src/components/editor/property/InputLiteral.jsx
  src/components/editor/property/InputLookupQA.jsx
  src/components/editor/property/InputLookupSinopia.jsx
  src/components/editor/property/InputURI.jsx
  src/components/editor/property/InputValue.jsx
  src/components/editor/property/LanguageButton.jsx
  src/components/editor/property/OutlineHeader.jsx
  src/components/editor/property/PropertyPanel.jsx
  src/components/editor/property/PropertyResourceTemplate.jsx
  src/components/editor/property/PropertyTemplateOutline.jsx
  src/components/editor/property/ResourceProperty.jsx
  src/reducers/index.js
  src/reducers/inputs.js
  src/selectors/resourceSelectors.js
Labels: BFF

#1154 Use bindActionCreators whereever possible
  __tests__/components/App.test.js
  __tests__/components/editor/GroupChoiceModal.test.js
  __tests__/components/editor/SaveAndPublishButton.test.js
  __tests__/components/editor/property/InputListLOC.test.js
  __tests__/components/editor/property/InputLiteral.test.js
  __tests__/components/editor/property/InputLookupQA.test.js
  __tests__/components/editor/property/InputLookupSinopia.test.js
  __tests__/components/editor/property/InputURI.test.js
  __tests__/components/editor/property/LanguageButton.test.js
  __tests__/components/load/LoadByRDFForm.test.js
  __tests__/components/load/LoadByURIForm.test.js
  src/components/App.jsx
  src/components/editor/Editor.jsx
  src/components/editor/GroupChoiceModal.jsx
  src/components/editor/RDFModal.jsx
  src/components/editor/SaveAndPublishButton.jsx
  src/components/editor/property/InputListLOC.jsx
  src/components/editor/property/InputLiteral.jsx
  src/components/editor/property/InputLookupQA.jsx
  src/components/editor/property/InputLookupSinopia.jsx
  src/components/editor/property/InputURI.jsx
  src/components/editor/property/LanguageButton.jsx
  src/components/editor/property/PropertyActionButtons.jsx
  src/components/editor/property/PropertyPanel.jsx
  src/components/load/LoadByRDFForm.jsx
  src/components/load/LoadByURIForm.jsx
  src/components/search/Search.jsx
  src/components/search/SearchResults.jsx
  src/components/search/SearchResultsPaging.jsx
  src/components/templates/ImportResourceTemplate.jsx
  src/components/templates/SinopiaResourceTemplates.jsx
Labels: BFF

#1159 Simplifies resource uri message, now that resource uri is available i…
  __tests__/actionCreators/resources.test.js
  __tests__/reducers/inputs.test.js
  src/actionCreators/resources.js
  src/actions/index.js
  src/components/editor/ResourceURIMessage.jsx
  src/reducers/index.js
  src/reducers/inputs.js
Labels: BFF

#1160 Make Add / Remove buttons have solid borders on panel.
  src/styles/main.css
Labels: BFF

#1158 Display error for bad prop template
  __tests__/ResourceValidator.test.js
  __tests__/__fixtures__/lookupWithValueTemplateRefs.json
  __tests__/fixtureLoaderHelper.js
  __tests__/integration/propertyTemplateMisconfigured.test.js
  src/ResourceValidator.js
  src/components/editor/property/PropertyComponent.jsx
  src/utilities/propertyTemplates.js
Labels: BFF, M4

#1157 Removes find node function from resource validator constructor.
  __tests__/ResourceValidator.test.js
  __tests__/integration/correctRdfInPreview/literalPropertyTemplates.test.js
  src/ResourceValidator.js
  src/reducers/inputs.js
Labels: BFF

#1155 Switch from prov:wasGeneratedBy
  __tests__/GraphBuilder.test.js
  __tests__/ResourceStateBuilder.test.js
  __tests__/actionCreators/resources.test.js
  __tests__/integration/correctRdfInPreview/literalPropertyTemplates.test.js
  __tests__/integration/loadRDF.test.js
  __tests__/selectors/resourceSelectors.test.js
  src/GraphBuilder.js
  src/ResourceStateBuilder.js
Labels: BFF

#1119 Lookup context api
  __tests__/__fixtures__/DiscogsExample.json
  __tests__/__fixtures__/ShareVDEExample.json
  __tests__/components/editor/property/InputLookupQA.test.js
  __tests__/fixtureLoaderHelper.js
  src/components/editor/property/InputLookupQA.jsx
  src/lib/apidoc.json
  static/lookupConfig.json
Labels: BFF, enhancement

#1161 Extract QA search to a thunk
  __tests__/actionCreators/qa.test.js
  __tests__/components/editor/property/InputLookupQA.test.js
  src/actionCreators/qa.js
  src/actions/index.js
  src/components/editor/property/InputLookupQA.jsx
  src/reducers/entities.js
  src/reducers/index.js
  src/store.js
Labels: BFF

#1163 Make InputLookupQA a functional component
  __tests__/components/editor/property/InputLookupQA.test.js
  src/components/editor/property/InputLookupQA.jsx
Labels: BFF

#930 remove subauthorities for LCSH
  __tests__/__fixtures__/MonographInstance.json
  __tests__/__fixtures__/adminMetadata.json
  __tests__/integration/loginHelper.js
  static/lookupConfig.json
Labels: Authorities, BFF, M4

#1165 Changes label and uri fields expected from ES.
  __tests__/components/editor/property/InputLookupSinopia.test.js
  package-lock.json
  src/components/editor/property/InputLookupSinopia.jsx
  src/sinopiaServer.js
Labels: BFF

#1125 Rendering context for lookup in separate component
  __tests__/__fixtures__/MonographInstance.json
  __tests__/components/editor/property/RenderLookupContext.test.js
  src/components/editor/property/InputLookupQA.jsx
  src/components/editor/property/RenderLookupContext.jsx
  src/styles/main.css
Labels: BFF, enhancement

#1178 Fixed proptype for InputLookupQA.
  src/components/editor/property/InputLookupQA.jsx
Labels: BFF

#1167 Avoid 404 flash.
  __tests__/components/App.test.js
  src/components/App.jsx
Labels: BFF

#1177 Fixes display of validation errors. Adds integration test for validat…
  __tests__/integration/correctRdfInPreview/literalPropertyTemplates.test.js
  __tests__/integration/validationErrors.test.js
  src/selectors/resourceSelectors.js
Labels: BFF

#1180 Label is now the correct field to grab from the search results
  src/sinopiaServer.js
Labels: BFF, M4

#1183 Builds graph with relative URI rather than absolute URI.
  __tests__/GraphBuilder.test.js
  __tests__/actionCreators/resources.test.js
  src/GraphBuilder.js
  src/actionCreators/resources.js
Labels: BFF

#1179 Fixes prompt when toggling help.
  src/components/App.jsx
  src/components/editor/Editor.jsx
Labels: BFF

#1189 Provides reason when calling retrieveError.
  src/actionCreators/resourceTemplates.js
Labels: BFF

#1190 Added wildcard help text to InputLookupSinopia and Search.
  __tests__/components/editor/property/InputLookupSinopia.test.js
  src/components/editor/property/InputListLOC.jsx
  src/components/editor/property/InputLiteral.jsx
  src/components/editor/property/InputLookupQA.jsx
  src/components/editor/property/InputLookupSinopia.jsx
  src/components/editor/property/InputURI.jsx
  src/components/editor/property/OutlineHeader.jsx
  src/components/search/Search.jsx
Labels: BFF

#1192 Give a more clear error when the lookup is misconfigured
  __tests__/integration/propertyTemplateMisconfigured.test.js
  __tests__/utilities/propertyTemplates.test.js
  src/components/editor/property/PropertyComponent.jsx
  src/utilities/propertyTemplates.js
Labels: BFF

#1195 New version 0.3.10
  package-lock.json
  package.json
Labels: BFF, M4

#1197 Sinopia MVP 1.0.0 Release
  __tests__/components/home/NewsItem.test.js
  package-lock.json
  package.json
  src/components/home/NewsItem.jsx
Labels: BFF, M4

#1191 README and Tagged Release Template Issue changes
  .github/ISSUE_TEMPLATE/tagged-release.md
  README.md
Labels: BFF, M4

#1206 Resets Editor Validations
  __tests__/reducers/index.test.js
  src/reducers/index.js
Labels: BFF

#1253 Adding resource templates that are being used for User Feedback testing
  __tests__/__fixtures__/Harvard_rt_test_userfeedback.json
  __tests__/__fixtures__/Harvard_rt_test_userfeedback_instance.json
  __tests__/__fixtures__/Harvard_rt_test_userfeedback_item.json
  __tests__/__fixtures__/Harvard_rt_test_userfeedback_worktitle.json
  __tests__/__fixtures__/harvard_rt_test_userfeedback_contribution3.json
  __tests__/__fixtures__/lc_RT_bf2_Agent_Role.json
  __tests__/__fixtures__/sinopia_RT_userfeedback_Agents_Contribution.json
  __tests__/__fixtures__/sinopia_resourceTemplate_bf2_Item_Access.json
  __tests__/__fixtures__/sinopia_resourceTemplate_bf2_Item_Chronology.json
  __tests__/__fixtures__/sinopia_resourceTemplate_bf2_Item_Enumeration.json
  __tests__/__fixtures__/sinopia_resourceTemplate_bf2_Item_Retention.json
  __tests__/__fixtures__/sinopia_resourceTemplate_bf2_Item_Use.json
  __tests__/__fixtures__/sinopia_resourceTemplate_bf2_ParallelTitle.json
  __tests__/__fixtures__/sinopia_resourceTemplate_bf2_Title.json
  __tests__/__fixtures__/sinopia_resourceTemplate_bf2_Title_Note.json
  __tests__/__fixtures__/sinopia_resourceTemplate_bf2_Title_VarTitle.json
  __tests__/__fixtures__/sinopia_resourceTemplate_bflc_TranscribedTitle.json
  __tests__/__fixtures__/stanford_RT_BF2_DistributionInfo.json
  __tests__/__fixtures__/stanford_RT_BF2_Identifiers_AccessionCopyNo.json
  __tests__/__fixtures__/stanford_RT_BF2_Identifiers_Barcode.json
  __tests__/__fixtures__/stanford_RT_BF2_Identifiers_DDC.json
  __tests__/__fixtures__/stanford_RT_BF2_Identifiers_ISBN.json
  __tests__/__fixtures__/stanford_RT_BF2_Identifiers_ISSN.json
  __tests__/__fixtures__/stanford_RT_BF2_Identifiers_LC.json
  __tests__/__fixtures__/stanford_RT_BF2_Identifiers_LCCN.json
  __tests__/__fixtures__/stanford_RT_BF2_Identifiers_Local.json
  __tests__/__fixtures__/stanford_RT_BF2_Identifiers_Other.json
  __tests__/__fixtures__/stanford_RT_BF2_Identifiers_Source.json
  __tests__/__fixtures__/stanford_RT_BF2_ManufactureInfo.json
  __tests__/__fixtures__/stanford_RT_BF2_Monograph_Item.json
  __tests__/__fixtures__/stanford_RT_BF2_Note.json
  __tests__/__fixtures__/stanford_RT_BF2_ProductionInfo.json
  __tests__/__fixtures__/stanford_RT_BF2_ProvisionName.json
  __tests__/__fixtures__/stanford_RT_BF2_ProvisionPlace.json
  __tests__/__fixtures__/stanford_RT_BF2_PublicationInfo.json
  __tests__/fixtureLoaderHelper.js
Labels: BFF, templates

#1272 Updating packages
  package-lock.json
  package.json
Labels: BFF
