Repository LD4P/sinopia_editor, pull requests merged in 2019-06, with the labels that each got.

#608 Fix typo.
  __tests__/components/editor/InputLang.test.js
  src/components/editor/InputLang.jsx
Labels: M4

#610 Remove unnecessary Object.create
  src/reducers/index.js
Labels: BFF, M4

#605 Convert the state to RDF
  .eslintrc.js
  __tests__/GraphBuilder.test.js
  src/GraphBuilder.js
Labels: BFF, M4

#611 Set the RDF class in the graph
  __tests__/GraphBuilder.test.js
  __tests__/reducers/index.test.js
  src/GraphBuilder.js
  src/reducers/index.js
Labels: BFF, M4

#612 Adds save and cancel buttons to RDF Modal
  __tests__/components/editor/Editor.test.js
  __tests__/components/editor/ImportFileZone.test.js
  __tests__/components/editor/RDFModal.test.js
  __tests__/sinopiaServer.test.js
  src/components/editor/Editor.jsx
  src/components/editor/RDFModal.jsx
  src/sinopiaServer.js
Labels: M4

#618 Omit type assertion since the permission template doesn't support it
  src/GraphBuilder.js
  src/reducers/index.js
Labels: M4, needs review

#615 Allows re-editing of literals.
  .eslintrc.js
  __tests__/components/editor/InputLiteral.test.js
  src/components/editor/InputLiteral.jsx
Labels: BFF, M4

#623 Render a warning when expanding a template w/ missing RT
  .eslintrc.js
  __tests__/components/editor/ImportFileZone.test.js
  __tests__/components/editor/ResourceProperty.test.js
  __tests__/reducers/index.test.js
  src/components/editor/ImportFileZone.jsx
  src/components/editor/ResourceProperty.jsx
  src/reducers/index.js
Labels: M4

#624 Update Coveralls badge and tweak description in README
  README.md
Labels: M4

#620 Create a modal to get user input for choosing a sinopia group
  __tests__/components/editor/GroupChoiceModal.test.js
  __tests__/components/editor/RDFModal.test.js
  __tests__/integration/previewSaveRDF.test.js
  __tests__/sinopiaServer.test.js
  src/Config.js
  src/components/editor/Editor.jsx
  src/components/editor/GroupChoiceModal.jsx
  src/components/editor/RDFModal.jsx
  src/sinopiaServer.js
  src/styles/main.css
Labels: M4

#632 Bug fixes and new feature additions in release.
  package.json
Labels: M4

#644 Don't allow constructors to change state
  src/components/editor/property/InputListLOC.jsx
Labels: BFF, M4, needs review

#657 Remove unused stylesheet
  src/css/bootstrap.css
Labels: BFF, M4, needs review

#655 Use the built-in close button
  src/components/editor/GroupChoiceModal.jsx
Labels: M4, needs review

#647 Remove properties that do not conform to the schema
  static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/MonographInstance.json
Labels: M4, needs review

#658 Fixes reduxPath building and corrects GraphBuilder assumption about n…
  __tests__/GraphBuilder.test.js
  __tests__/components/editor/property/PropertyResourceTemplate.test.js
  __tests__/components/editor/property/ResourceProperty.test.js
  src/GraphBuilder.js
  src/components/editor/property/PropertyResourceTemplate.jsx
  src/components/editor/property/PropertyTemplateOutline.jsx
  src/components/editor/property/ResourceProperty.jsx
Labels: needs review

#654 Remove unused state and make RDFModal functional
  src/components/editor/RDFModal.jsx
Labels: M4, needs review

#659 Filter ld4p out of the list of groups you can save into
  __tests__/components/editor/GroupChoiceModal.test.js
  src/components/editor/Editor.jsx
  src/components/editor/GroupChoiceModal.jsx
Labels: BFF, M4, needs review

#652 Only generate the RDF when the button is pressed to preview
  __tests__/components/editor/GroupChoiceModal.test.js
  __tests__/components/editor/RDFModal.test.js
  __tests__/reducers/index.test.js
  src/components/editor/Editor.jsx
  src/components/editor/GroupChoiceModal.jsx
  src/components/editor/RDFModal.jsx
  src/reducers/index.js
Labels: M4, needs review

#665 Save resource to Trellis
  __tests__/GraphBuilder.test.js
  __tests__/reducers/index.test.js
  __tests__/reducers/inputs.test.js
  __tests__/sinopiaServer.test.js
  src/GraphBuilder.js
  src/actions/index.js
  src/components/editor/Editor.jsx
  src/reducers/index.js
  src/reducers/inputs.js
  src/sinopiaServer.js
Labels: BFF, M4, needs review

#642 Fixes language input (you know, so that you can input a language) and…
  __tests__/components/editor/property/InputLang.test.js
  __tests__/components/editor/property/InputLiteral.test.js
  __tests__/reducers/index.test.js
  __tests__/reducers/lang.test.js
  src/Utilities.js
  src/components/editor/Editor.jsx
  src/components/editor/property/InputLang.jsx
  src/components/editor/property/InputLiteral.jsx
  src/reducers/index.js
  src/reducers/inputs.js
  src/reducers/lang.js
Labels: BFF, M4

#676 Change default display label for Typeahead component
  __tests__/components/editor/property/InputLang.test.js
  src/components/editor/property/InputLang.jsx
Labels: BFF, M4, needs review

#678 Change button text so as not to be misleading
  __tests__/components/editor/ImportFileZone.test.js
  src/components/editor/ImportFileZone.jsx
Labels: BFF, M4, needs review

#680 Fix line to long eslint error
  src/components/editor/ImportFileZone.jsx
Labels: M4, bug, needs review

#681 [refactor] Simplify populatePropertyDefaults
  package.json
  src/reducers/index.js
Labels: BFF, M4

#671 Simple integration test for unauthenticated users
  __tests__/integration/unauthenticatedNavigation.test.js
Labels: BFF, M4

#684 Fix undefined label in the InputLookupQA component
  __tests__/Utilities.test.js
  __tests__/sinopiaServerSpoof.test.js
  src/Utilities.js
  src/sinopiaServerSpoof.js
  static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/RDAMainifestationMonograph.json
  static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/adminMetadata.json
  static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/adminMetadataStatus.json
  static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/rdaItemMonograph.json
Labels: BFF, M4, needs review

#685 Fixed add buttons.
  __tests__/GraphBuilder.test.js
  __tests__/components/editor/property/PropertyTemplateOutline.test.js
  __tests__/components/editor/property/ResourceProperty.test.js
  __tests__/integration/repeatableResources.test.js
  src/GraphBuilder.js
  src/components/editor/property/PropertyResourceTemplate.jsx
  src/components/editor/property/PropertyTemplateOutline.jsx
  src/components/editor/property/ResourceProperty.jsx
Labels: M4, needs review

#695 Add editor save button
  __tests__/components/editor/Editor.test.js
  __tests__/components/editor/RDFModal.test.js
  __tests__/integration/previewSaveRDF.test.js
  src/components/editor/Editor.jsx
  src/components/editor/RDFModal.jsx
  src/styles/main.css
Labels: BFF, M4, needs review

#686 Record the resource template responses into the Redux state
  __tests__/GraphBuilder.test.js
  __tests__/actions/index.test.js
  __tests__/components/editor/ResourceTemplateForm.test.js
  __tests__/components/editor/property/ResourceProperty.test.js
  __tests__/reducers/index.test.js
  src/GraphBuilder.js
  src/actions/index.js
  src/components/editor/ResourceTemplateForm.jsx
  src/components/editor/property/PropertyTemplateOutline.jsx
  src/components/editor/property/ResourceProperty.jsx
  src/reducers/index.js
  src/store.js
Labels: BFF, M4

#704 Fixed a bug where setBaseURI was not in the right redux path.
  __tests__/reducers/inputs.test.js
  src/reducers/index.js
  src/reducers/inputs.js
Labels: M4, bug, needs review

#706 Combine tests that depend on one another
  __tests__/integration/previewSaveRDF.test.js
Labels: BFF, M4

#640 [Refactor] rename getResourceTemplatePromise to resolveResourceTempla…
  __tests__/components/editor/ResourceTemplate.test.js
  src/components/editor/ResourceTemplate.jsx
Labels: BFF, M4, needs review

#708 Change propLabel to data-label
  __tests__/integration/repeatableResources.test.js
  src/components/editor/property/PropertyPanel.jsx
  src/components/editor/property/PropertyTemplateOutline.jsx
Labels: BFF, M4, needs review

#705 Refactor displayValidations and getPropertyTemplate to use findNode
  src/reducers/index.js
Labels: BFF, M4

#711 Create a new mock for each test
  __tests__/components/editor/property/InputLiteral.test.js
Labels: BFF, M4

#713 Refactor a test to match the reality of the reduxPath
  __tests__/reducers/inputs.test.js
Labels: M4, needs review

#714 Updated version and regenerated lock file
  package-lock.json
  package.json
Labels: BFF, M4

#702 For InputQA, switches from properties to state for propertyTemplate a…
  __tests__/Utilities.test.js
  __tests__/components/editor/property/PropertyComponent.test.js
  src/Utilities.js
  src/components/editor/property/InputLookupQA.jsx
  src/components/editor/property/PropertyComponent.jsx
Labels: BFF, M4

#716 Get resource template from redux store
  .eslintrc.js
  src/components/editor/ResourceTemplateForm.jsx
Labels: BFF, M4

#717 Display validations at the top level when validate is pressed.
  __tests__/Validator.test.js
  __tests__/actions/index.test.js
  __tests__/components/editor/Editor.test.js
  __tests__/components/editor/property/InputLiteral.test.js
  __tests__/reducers/inputs.test.js
  src/Validator.js
  src/actions/index.js
  src/components/editor/Editor.jsx
  src/components/editor/property/InputLiteral.jsx
  src/reducers/index.js
  src/reducers/inputs.js
  src/store.js
Labels: M4

#723 Remove unnecessary indirection
  src/components/editor/Editor.jsx
Labels: BFF, M4

#721 Add an intergration test for non-roman entry into a literal
  __tests__/integration/nestedResources.test.js
Labels: BFF, M4

#722 Move local editor state for showing group choice modal to the Redux s…
  __tests__/components/editor/Editor.test.js
  __tests__/components/editor/GroupChoiceModal.test.js
  __tests__/reducers/inputs.test.js
  src/actions/index.js
  src/components/editor/Editor.jsx
  src/components/editor/GroupChoiceModal.jsx
  src/reducers/index.js
  src/reducers/inputs.js
  src/store.js
Labels: BFF, M4

#725 Move state for showing preview to the redux store
  __tests__/components/editor/RDFModal.test.js
  __tests__/reducers/inputs.test.js
  src/actions/index.js
  src/components/editor/Editor.jsx
  src/components/editor/GroupChoiceModal.jsx
  src/components/editor/RDFModal.jsx
  src/reducers/index.js
  src/reducers/inputs.js
  src/store.js
Labels: BFF, M4

#728 Switch GroupChoiceModal to a functional style (without state)
  src/components/editor/GroupChoiceModal.jsx
Labels: BFF, M4

#738 Items must be properties or removing them doesn't cause re-render
  __tests__/components/editor/property/InputLiteral.test.js
  src/components/editor/property/InputLiteral.jsx
Labels: BFF, M4

#733 Validate when pressing the save button
  __tests__/GraphBuilder.test.js
  __tests__/Validator.test.js
  __tests__/actions/index.test.js
  __tests__/components/editor/Editor.test.js
  __tests__/integration/previewSaveRDF.test.js
  __tests__/reducers/inputs.test.js
  src/GraphBuilder.js
  src/Validator.js
  src/actions/index.js
  src/components/editor/Editor.jsx
  src/reducers/index.js
  src/reducers/inputs.js
Labels: BFF, M4, needs review

#742 Reduce indirection by inlining getAllRdf method
  __tests__/reducers/index.test.js
  src/components/editor/GroupChoiceModal.jsx
  src/components/editor/RDFModal.jsx
  src/reducers/index.js
Labels: M4

#734 Fix Blank Screen when performing a Lookup
  __tests__/Utilities.test.js
  __tests__/reducers/inputs.test.js
  src/Utilities.js
  src/reducers/index.js
  src/reducers/inputs.js
Labels: BFF, M4

#743 Install the babel module-resolver plugin
  .babelrc
  package-lock.json
  package.json
  src/components/CanvasMenu.jsx
  src/components/Header.jsx
  src/components/LoginPanel.jsx
  src/components/editor/Editor.jsx
  src/components/editor/GroupChoiceModal.jsx
  src/components/editor/Header.jsx
  src/components/editor/ImportFileZone.jsx
  src/components/editor/ImportResourceTemplate.jsx
  src/components/editor/RDFModal.jsx
  src/components/editor/ResourceTemplate.jsx
  src/components/editor/ResourceTemplateForm.jsx
  src/components/editor/SinopiaResourceTemplates.jsx
  src/components/editor/UpdateResourceModal.jsx
  src/components/editor/property/InputListLOC.jsx
  src/components/editor/property/InputLiteral.jsx
  src/components/editor/property/InputLookupQA.jsx
  src/components/editor/property/PropertyComponent.jsx
  src/components/editor/property/PropertyTemplateOutline.jsx
  src/components/editor/property/ResourceProperty.jsx
  src/reducers/index.js
  webpack.config.js
Labels: M4

#741 [Refactor] Organize the components into directories by routes
  __tests__/components/App.test.js
  __tests__/components/Header.test.js
  __tests__/components/browse/Browse.test.js
  __tests__/components/editor/Editor.test.js
  __tests__/components/editor/Header.test.js
  __tests__/components/home/DescPanel.test.js
  __tests__/components/home/Header.test.js
  __tests__/components/home/HomePage.test.js
  __tests__/components/home/NewsItem.test.js
  __tests__/components/home/NewsPanel.test.js
  __tests__/components/menu/CanvasMenu.test.js
  __tests__/components/templates/ImportFileZone.test.js
  __tests__/components/templates/ImportResourceTemplate.test.js
  __tests__/components/templates/SinopiaResourceTemplates.test.js
  __tests__/components/templates/UpdateResourceModal.test.js
  src/components/App.jsx
  src/components/Header.jsx
  src/components/RootContainer.jsx
  src/components/browse/Browse.jsx
  src/components/editor/Editor.jsx
  src/components/editor/Header.jsx
  src/components/home/DescPanel.jsx
  src/components/home/Header.jsx
  src/components/home/HomePage.jsx
  src/components/home/NewsItem.jsx
  src/components/home/NewsPanel.jsx
  src/components/menu/CanvasMenu.jsx
  src/components/templates/ImportFileZone.jsx
  src/components/templates/ImportResourceTemplate.jsx
  src/components/templates/SinopiaResourceTemplates.jsx
  src/components/templates/UpdateResourceModal.jsx
Labels: M4

#749 Move logic for saving to GroupChoiceModal from Editor
  __tests__/components/editor/GroupChoiceModal.test.js
  src/components/editor/Editor.jsx
  src/components/editor/GroupChoiceModal.jsx
  src/components/editor/RDFModal.jsx
Labels: BFF, M4

#737 Use Utility function in InputLiteral component to determine the boolean values from JSON strings
  src/components/editor/property/InputLiteral.jsx
Labels: BFF, needs review

#754 Convert the Editor component to a Function
  src/components/editor/Editor.jsx
  src/components/editor/ResourceTemplate.jsx
Labels: BFF, M4

#740 get the correct list of groups to display (and sort them in alphabetical order) when choosing where to save a resource
  __tests__/components/editor/GroupChoiceModal.test.js
  src/Config.js
  src/components/editor/GroupChoiceModal.jsx
Labels: needs review

#727 Do not add extra property rows when clicking the plus/add button.
  __tests__/components/editor/property/PropertyTemplateOutline.test.js
  src/components/editor/property/PropertyTemplateOutline.jsx
Labels: BFF, M4

#760 [Refactor] Extract search logic from render logic
  __tests__/components/editor/property/InputLookupQA.test.js
  src/components/editor/property/InputLookupQA.jsx
Labels: BFF, M4

#762 In lookup property require the lookupConfig
  __tests__/components/editor/property/InputLookupQA.test.js
  src/components/editor/property/InputLookupQA.jsx
Labels: BFF, M4

#756 Allow resources to be updated
  __tests__/actionCreators.test.js
  __tests__/components/editor/Editor.test.js
  __tests__/integration/previewSaveRDF.test.js
  __tests__/selectors/resourceSelectors.test.js
  package-lock.json
  package.json
  src/actionCreators.js
  src/actions/index.js
  src/components/editor/Editor.jsx
  src/selectors/resourceSelectors.js
  src/sinopiaServer.js
  src/store.js
Labels: BFF, M4

#759 Restore the ability for defaults to be used in a lookup
  __tests__/components/editor/property/InputLookupQA.test.js
  src/components/editor/property/InputLookupQA.jsx
Labels: BFF, M4

#735 ResourceProperty: separate state changes from rendering
  .eslintrc.js
  src/components/editor/property/ResourceProperty.jsx
Labels: M4

#773 Export language tags to RDF
  __tests__/GraphBuilder.test.js
  __tests__/components/editor/property/InputLang.test.js
  __tests__/reducers/index.test.js
  src/GraphBuilder.js
  src/Utilities.js
  src/components/editor/property/InputLang.jsx
Labels: BFF, M4

#774 don't bother logging to console when there are no defaults defined for a property template
  __tests__/components/editor/property/InputLookupQA.test.js
  src/components/editor/property/InputLookupQA.jsx
Labels: M4

#777 fix typo
  __tests__/integration/nestedResources.test.js
Labels: needs review

#768 Fixes bug where subsequently selected resource templates are appended to selectorReducer.resource
  __tests__/reducers/index.test.js
  src/components/editor/property/ResourceProperty.jsx
  src/reducers/index.js
Labels: BFF

#779 Remove unnecessary prop from tests
  __tests__/components/editor/property/InputLiteral.test.js
  __tests__/components/editor/property/PropertyComponent.test.js
Labels: M4

#776 Document the setItemsOrSelections reducer function
  src/reducers/inputs.js
Labels: M4

#780 Copyright statement for resourceSelectors.js
  src/selectors/resourceSelectors.js
Labels: BFF, M4

#782 Close the previewRDF modal if validations fail
  __tests__/reducers/inputs.test.js
  src/reducers/inputs.js
Labels: M4

#791 Test for structure not for equality
  __tests__/sinopiaServerSpoof.test.js
Labels: BFF, M4

#792 Simplify removing an item.
  __tests__/actions/index.test.js
  src/actions/index.js
  src/components/editor/property/InputLiteral.jsx
Labels: BFF, M4

#793 Use webpack to build both dev and prod servers
  .eslintignore
  .eslintrc.js
  README.md
  __tests__/components/home/Header.test.js
  docker-compose.yml
  jest-puppeteer.config.js
  package-lock.json
  package.json
  server.js
  src/components/App.jsx
  src/components/home/Header.jsx
  src/css/main.css
  src/css/typeahead.css
  src/html/index.html
  src/img/editorheaderbg.png
  src/img/home-background.png
  src/img/sinopia-logo.png
  src/index.js
  src/server/server.dev.js
  src/server/server.prod.js
  src/server/serverRoutes.js
  src/styles/editorsinopialogo.png
  src/versoSpoof.js
  static/spoofedFilesFromServer/from_verso/data/profiles/BIBFRAME_2.0_Admin_Metadata.json
  static/spoofedFilesFromServer/from_verso/data/profiles/BIBFRAME_2.0_Agents.json
  static/spoofedFilesFromServer/from_verso/data/profiles/BIBFRAME_2.0_Agents_Contribution.json
  static/spoofedFilesFromServer/from_verso/data/profiles/BIBFRAME_2.0_Agents_Primary_Contribution.json
  static/spoofedFilesFromServer/from_verso/data/profiles/BIBFRAME_2.0_Cartographic.json
  static/spoofedFilesFromServer/from_verso/data/profiles/BIBFRAME_2.0_DDC.json
  static/spoofedFilesFromServer/from_verso/data/profiles/BIBFRAME_2.0_Extra_menus.json
  static/spoofedFilesFromServer/from_verso/data/profiles/BIBFRAME_2.0_Form.json
  static/spoofedFilesFromServer/from_verso/data/profiles/BIBFRAME_2.0_Identifiers.json
  static/spoofedFilesFromServer/from_verso/data/profiles/BIBFRAME_2.0_Item.json
  static/spoofedFilesFromServer/from_verso/data/profiles/BIBFRAME_2.0_LCC.json
  static/spoofedFilesFromServer/from_verso/data/profiles/BIBFRAME_2.0_Language.json
  static/spoofedFilesFromServer/from_verso/data/profiles/BIBFRAME_2.0_Monograph.json
  static/spoofedFilesFromServer/from_verso/data/profiles/BIBFRAME_2.0_Moving_Image-35mm_Feature_Film.json
  static/spoofedFilesFromServer/from_verso/data/profiles/BIBFRAME_2.0_Moving_Image-BluRay_DVD.json
  static/spoofedFilesFromServer/from_verso/data/profiles/BIBFRAME_2.0_Notated_Music.json
  static/spoofedFilesFromServer/from_verso/data/profiles/BIBFRAME_2.0_Note.json
  static/spoofedFilesFromServer/from_verso/data/profiles/BIBFRAME_2.0_Place.json
  static/spoofedFilesFromServer/from_verso/data/profiles/BIBFRAME_2.0_Publication,_Distribution,_Manufacturer_Activity.json
  static/spoofedFilesFromServer/from_verso/data/profiles/BIBFRAME_2.0_RWO.json
  static/spoofedFilesFromServer/from_verso/data/profiles/BIBFRAME_2.0_Rare_Materials.json
  static/spoofedFilesFromServer/from_verso/data/profiles/BIBFRAME_2.0_Related_Works_and_Expressions.json
  static/spoofedFilesFromServer/from_verso/data/profiles/BIBFRAME_2.0_Serial.json
  static/spoofedFilesFromServer/from_verso/data/profiles/BIBFRAME_2.0_Series_Information.json
  static/spoofedFilesFromServer/from_verso/data/profiles/BIBFRAME_2.0_Sound_Recording-Analog.json
  static/spoofedFilesFromServer/from_verso/data/profiles/BIBFRAME_2.0_Sound_Recording-Audio_CD-R.json
  static/spoofedFilesFromServer/from_verso/data/profiles/BIBFRAME_2.0_Sound_Recording-Audio_CD.json
  static/spoofedFilesFromServer/from_verso/data/profiles/BIBFRAME_2.0_Title_Information.json
  static/spoofedFilesFromServer/from_verso/data/profiles/BIBFRAME_2.0_Topic.json
  static/spoofedFilesFromServer/from_verso/data/profiles/PMO_Medium_of_Performance.json
  webpack.config.js
  webpack.dev.config.js
  webpack.prod.config.js
  webpack.server.config.js
Labels: M4

#796 Remove unused property from test
  __tests__/components/editor/property/InputLiteral.test.js
Labels: M4

#770 Fix empty tooltip and missing required tooltip
  .eslintrc.js
  __tests__/components/editor/property/PropertyLabel.test.js
  __tests__/components/editor/property/RequiredSuperscript.test.js
  src/components/editor/property/PropertyLabel.jsx
  src/components/editor/property/RequiredSuperscript.jsx
Labels: BFF, M4, needs review

#798 Add generatedBy triples to the graph
  __tests__/GraphBuilder.test.js
  src/GraphBuilder.js
Labels: BFF, M4

#799 Add an aria-lable so a screen reader will understand the sup tag
  src/components/editor/property/RequiredSuperscript.jsx
Labels: BFF, M4

#789 Add a uri component for entering in resources directly
  __tests__/components/editor/RDFModal.test.js
  __tests__/components/editor/property/InputURI.test.js
  __tests__/components/editor/property/PropertyComponent.test.js
  src/components/editor/property/InputURI.jsx
  src/components/editor/property/PropertyComponent.jsx
  src/reducers/inputs.js
  src/sinopiaServerSpoof.js
  static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/Item.json
  static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/OnlyEquivalent.json
Labels: BFF, M4

#801 Version 0.3.3
  package-lock.json
  package.json
Labels: BFF, M4

#786 Fixtures not spoof
  .circleci/config.yml
  .dockerignore
  Dockerfile
  README.md
  __tests__/Config.test.js
  __tests__/__fixtures__/Barcode.json
  __tests__/__fixtures__/DDC.json
  __tests__/__fixtures__/Item.json
  __tests__/__fixtures__/ItemAcqSource.json
  __tests__/__fixtures__/ItemChronology.json
  __tests__/__fixtures__/ItemEnumeration.json
  __tests__/__fixtures__/ItemRetention.json
  __tests__/__fixtures__/LCCN.json
  __tests__/__fixtures__/MonographInstance.json
  __tests__/__fixtures__/MonographWork.json
  __tests__/__fixtures__/Note(Profile).json
  __tests__/__fixtures__/Note.json
  __tests__/__fixtures__/OnlyEquivalent.json
  __tests__/__fixtures__/ParallelTitle.json
  __tests__/__fixtures__/RDAMainifestationMonograph.json
  __tests__/__fixtures__/Shelfmark.json
  __tests__/__fixtures__/Title.json
  __tests__/__fixtures__/TitleNote.json
  __tests__/__fixtures__/TranscribedTitle.json
  __tests__/__fixtures__/VarTitle.json
  __tests__/__fixtures__/WorkTitle.json
  __tests__/__fixtures__/WorkVariantTitle.json
  __tests__/__fixtures__/adminMetadata.json
  __tests__/__fixtures__/adminMetadataStatus.json
  __tests__/__fixtures__/rdaItemMonograph.json
  __tests__/components/editor/ResourceTemplate.test.js
  __tests__/fixtureLoaderHelper.js
  __tests__/fixtureLoaderHelper.test.js
  __tests__/sinopiaServer.test.js
  docker-compose.yml
  jest-puppeteer.config.js
  package.json
  src/Config.js
  src/components/editor/ResourceTemplateForm.jsx
  src/sinopiaServer.js
  src/sinopiaServerSpoof.js
  webpack.config.js
Labels: M4

#807 docker builds can use defaults for some env vars
  .circleci/config.yml
  README.md
Labels: M4

#812 Remove unused prop-type
  src/components/editor/ResourceTemplate.jsx
Labels: BFF, M4

#809 simplify fixture loading
  .dockerignore
  __tests__/fixtureLoaderHelper.js
  package.json
  src/versoSpoof.js
  webpack.config.js
Labels: M4

#811 setResourceTemplate should clear the editor state
  __tests__/reducers/index.test.js
  src/reducers/index.js
Labels: BFF, M4

#814 Demonstrate a lightweight pattern for cross-environment routes
  server.js
  webpack.config.js
Labels: M4

#819 Salvage useful bits of #793
  .eslintignore
  README.md
  docker-compose.yml
  server.js
  webpack.config.js
Labels: M4, debt

#821 cleanup imports to make them consistent across codebase
  __tests__/actions/index.test.js
  __tests__/components/Footer.test.js
  __tests__/components/LoginPanel.test.js
  __tests__/components/RootComponent.test.js
  __tests__/components/editor/ResourceTemplate.test.js
  __tests__/components/editor/ResourceTemplateForm.test.js
  __tests__/integration/loginHelper.js
  __tests__/reducers/authenticate.test.js
  __tests__/reducers/lookups.test.js
  src/components/home/Header.jsx
Labels: needs review

#813 Make ResourceTemplateForm a connected component
  __tests__/components/editor/ResourceTemplate.test.js
  __tests__/components/editor/ResourceTemplateForm.test.js
  src/components/editor/ResourceTemplate.jsx
  src/components/editor/ResourceTemplateForm.jsx
Labels: BFF, M4

#827 Remove some unused state variables
  src/components/editor/ResourceTemplateForm.jsx
Labels: BFF, M4

#830 Refactor so that PropertyResourceTemplate makes the child rows
  __tests__/components/editor/ResourceTemplateForm.test.js
  __tests__/components/editor/property/PropertyResourceTemplate.test.js
  src/components/editor/ResourceTemplateForm.jsx
  src/components/editor/property/PropertyResourceTemplate.jsx
Labels: BFF, M4

#834 Refactor PropertyActionButtons not to have the AddButton subcomp…
  __tests__/components/editor/property/PropertyActionButtons.test.js
  __tests__/components/editor/property/PropertyResourceTemplate.test.js
  src/components/editor/property/PropertyActionButtons.jsx
Labels: BFF, M4

#815 Use thunks for loading the root resource template
  __tests__/components/editor/ResourceTemplate.test.js
  src/actionCreators.js
  src/actions/index.js
  src/components/editor/ResourceTemplate.jsx
  src/components/editor/ResourceTemplateForm.jsx
  src/reducers/index.js
Labels: BFF, M4

#822 swap the group col for author and remark ("guiding statement") cols in the template list page (/templates)
  __tests__/components/templates/SinopiaResourceTemplates.test.js
  src/components/templates/SinopiaResourceTemplates.jsx
Labels: needs review

#816 correct rdf "acceptance" tests for literals
  __tests__/__fixtures__/literalNoRepeatDefaultBoth.json
  __tests__/__fixtures__/literalNoRepeatDefaultLiteralNonEnglish.json
  __tests__/__fixtures__/literalNoRepeatDefaultLiteralOnly.json
  __tests__/__fixtures__/literalNoRepeatDefaultUriOnly.json
  __tests__/__fixtures__/literalNoRepeatNoDefault.json
  __tests__/__fixtures__/literalRepeat2DefaultsBoth.json
  __tests__/__fixtures__/literalRepeat2DefaultsLiteralNonEnglish.json
  __tests__/__fixtures__/literalRepeat2DefaultsLiteralOnly.json
  __tests__/__fixtures__/literalRepeat2DefaultsMixed.json
  __tests__/__fixtures__/literalRepeat2DefaultsUriOnly.json
  __tests__/__fixtures__/literalRepeatDefaultBoth.json
  __tests__/__fixtures__/literalRepeatDefaultLiteralNonEnglish.json
  __tests__/__fixtures__/literalRepeatDefaultLiteralOnly.json
  __tests__/__fixtures__/literalRepeatDefaultUriOnly.json
  __tests__/__fixtures__/literalRepeatNoDefault.json
  __tests__/fixtureLoaderHelper.js
  __tests__/integration/correctRdfInPreview/literalPropertyTemplates.test.js
Labels: M4, needs review

#820 fix repeated placeholder text for input literals in RT where propertyURI is repeated but propertyLabel differs
  __tests__/__fixtures__/propertyURIRepeated.json
  __tests__/fixtureLoaderHelper.js
  __tests__/integration/repeatedPropertyURI.js
  src/components/editor/property/InputLiteral.jsx
  src/components/editor/property/PropertyComponent.jsx
Labels: needs review

#841 MonographInstance fixture: remove duplicate property
  __tests__/__fixtures__/MonographInstance.json
Labels: M4

#842 Amcollie 766 jmartin followon
  src/actions/index.js
  src/components/editor/ResourceTemplate.jsx
  src/components/editor/ResourceURIMessage.jsx
Labels: needs review

#843 tests: if setup or tear down is async, no need for explicit return
  __tests__/integration/correctRdfInPreview/literalPropertyTemplates.test.js
  __tests__/integration/landingPage.test.js
  __tests__/integration/nestedResources.test.js
  __tests__/integration/previewSaveRDF.test.js
  __tests__/integration/repeatableResources.test.js
  __tests__/integration/saveIncompleteRDF.test.js
  __tests__/integration/schemaValidation.test.js
  __tests__/integration/unauthenticatedNavigation.test.js
  __tests__/integration/verifyPreviewRDF.test.js
Labels: debt, tests

#845 Set method complexity to fix eslint in build
  src/reducers/index.js
Labels: M4

#846 Ignore .env file when building docker images
  .dockerignore
Labels: M4

#853 ResourceTemplate: get rt label from redux entities rather than a…
  __tests__/components/editor/ResourceTemplate.test.js
  __tests__/integration/verifyTemplateTitle.test.js
  src/components/editor/ResourceTemplate.jsx
  src/reducers/index.js
Labels: M4

#856 InputListLOC uses redux state for propertyTemplate and lookupConfig
  __tests__/components/editor/property/InputListLOC.test.js
  __tests__/integration/previewRDFHelper.js
  src/components/editor/property/InputListLOC.jsx
  src/components/editor/property/InputLookupQA.jsx
  src/components/editor/property/PropertyComponent.jsx
Labels: M4
