Repository LD4P/sinopia_editor, pull requests merged in 2019-05, with the labels that each got.

#490 two comment tweaks
  src/components/HomePage.jsx
  src/reducers/index.js
Labels: needs review

#492 PropertyActionButtons: AddButton, MintButton are components
  __tests__/components/editor/PropertyActionButtons.test.js
  __tests__/components/editor/PropertyTemplateOutline.test.js
  src/components/editor/PropertyActionButtons.jsx
Labels: M3, needs review

#491 Going directly to editor route redirects to the "Resource Templates" tab
  __tests__/components/App.test.js
  __tests__/sinopiaServer.test.js
  src/components/App.jsx
  src/components/editor/Editor.jsx
  src/components/editor/ResourceTemplateForm.jsx
  src/components/editor/SinopiaResourceTemplates.jsx
  src/sinopiaServer.js
Labels: needs review

#497 More test cleanup
  __tests__/components/editor/OutlineHeader.test.js
  __tests__/components/editor/PropertyTemplateOutline.test.js
  src/components/editor/InputLiteral.jsx
Labels: M3, needs review

#499 ResourceTemplateForm.test: skip tests giving false positives
  __tests__/components/editor/PropertyTemplateOutline.test.js
  __tests__/components/editor/ResourceTemplateForm.test.js
  src/components/editor/PropertyTemplateOutline.jsx
  src/components/editor/ResourceTemplateForm.jsx
Labels: M3, needs review

#502 Fixes various verbose error messages and warnings when running tests
  __tests__/components/editor/InputLookupQA.test.js
  __tests__/components/editor/PropertyResourceTemplate.test.js
  __tests__/integration/landingPage.test.js
  __tests__/integration/schemaValidation.test.js
  __tests__/sinopiaServer.test.js
  jest-puppeteer.config.js
  src/components/editor/InputLiteral.jsx
  src/components/editor/InputLookupQA.jsx
  src/sinopiaServer.js
  static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/DDC.json
Labels: needs review

#493 Simplifying Reducers to fix blocking bug
  __tests__/components/editor/InputLiteral.test.js
  __tests__/components/editor/PropertyResourceTemplate.test.js
  __tests__/components/editor/PropertyTemplateOutline.test.js
  __tests__/components/editor/ResourceTemplateForm.test.js
  __tests__/reducers/index.test.js
  __tests__/reducers/literal.test.js
  src/components/editor/InputLiteral.jsx
  src/components/editor/PropertyResourceTemplate.jsx
  src/components/editor/PropertyTemplateOutline.jsx
  src/components/editor/ResourceTemplateForm.jsx
  src/reducers/index.js
  src/reducers/literal.js
Labels: M3, needs review

#505 Remove vestiges of wireframed resource template components
  __tests__/components/editor/ResourceTemplate.test.js
  src/components/editor/Editor.jsx
  src/components/editor/ResourceTemplate.jsx
  static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/MonographInstance.json
Labels: needs review

#504 Refactoring
  __tests__/components/editor/InputLiteral.test.js
  __tests__/components/editor/PropertyTemplateOutline.test.js
  package.json
  src/components/editor/PropertyTemplateOutline.jsx
Labels: needs review

#514 Removes bullet list of groups retrieved from Trellis
  __tests__/components/editor/SinopiaResourceTemplates.test.js
  src/components/editor/SinopiaResourceTemplates.jsx
Labels: M3, needs review

#512 Document how to deploy the editor to the AWS development environment
  README.md
Labels: M3, needs review

#513 Inputlistloc selector reducer
  __tests__/components/editor/InputListLOC.test.js
  __tests__/reducers/inputs.test.js
  src/components/editor/InputListLOC.jsx
  src/components/editor/ResourceTemplateForm.jsx
  src/reducers/index.js
  src/reducers/inputs.js
Labels: needs review

#515 Handles missing valueConstraint and valueTemplateRef in PropertyTemplateOutline
  __tests__/components/editor/PropertyTemplateOutline.test.js
  src/components/editor/PropertyTemplateOutline.jsx
Labels: M3, needs review

#522 Update docker-compose config for Trellis and ACL components
  docker-compose.yml
Labels: M3, needs review

#523 Missing templates
  __tests__/components/editor/ResourceTemplateForm.test.js
  src/Utilities.js
  src/components/editor/ImportResourceTemplate.jsx
  src/components/editor/PropertyTemplateOutline.jsx
  src/components/editor/ResourceTemplateForm.jsx
  src/components/editor/SinopiaResourceTemplates.jsx
  src/components/editor/UpdateResourceModal.jsx
Labels: M3, needs review

#525 Refactor and fix resource template components
  __mocks__/SinopiaClientErrorFake.js
  __mocks__/SinopiaClientSuccessFake.js
  __tests__/components/editor/ImportResourceTemplate.test.js
  __tests__/components/editor/SinopiaResourceTemplates.test.js
  __tests__/components/editor/UpdateResourceModal.test.js
  __tests__/reducers/inputs.test.js
  jest-puppeteer.config.js
  package-lock.json
  package.json
  src/components/Footer.jsx
  src/components/editor/ImportResourceTemplate.jsx
  src/components/editor/SinopiaResourceTemplates.jsx
  src/components/editor/UpdateResourceModal.jsx
  src/sinopiaServer.js
Labels: M3, needs review

#460 Manage sessions using amplify sdk
  README.md
  __tests__/Config.test.js
  __tests__/LoginData.test.js
  __tests__/Logout.test.js
  __tests__/actions/index.test.js
  __tests__/components/App.test.js
  __tests__/components/HomePage.test.js
  __tests__/components/Login.test.js
  __tests__/components/LoginPanel.test.js
  __tests__/components/editor/Editor.test.js
  __tests__/components/editor/ImportResourceTemplate.test.js
  __tests__/integration/schemaValidation.test.js
  __tests__/localStorage.test.js
  __tests__/reducers/authenticate.test.js
  __tests__/reducers/index.test.js
  package-lock.json
  package.json
  src/CognitoUtils.js
  src/Config.js
  src/LoginData.js
  src/Logout.js
  src/actions/index.js
  src/components/App.jsx
  src/components/HomePage.jsx
  src/components/Login.jsx
  src/components/LoginPanel.jsx
  src/components/NewsPanel.jsx
  src/components/editor/Editor.jsx
  src/components/editor/ImportResourceTemplate.jsx
  src/localStorage.js
  src/reducers/authenticate.js
  src/sinopiaServer.js
  src/store.js
Labels: M3, needs review

#538 Fix resource template table updates
  __tests__/components/editor/ImportFileZone.test.js
  __tests__/components/editor/ImportResourceTemplate.test.js
  src/components/editor/ImportFileZone.jsx
  src/components/editor/ImportResourceTemplate.jsx
  src/components/editor/SinopiaResourceTemplates.jsx
Labels: M3

#542 Check whether server has new templates when updating SinopiaResourceTemplates
  .eslintignore
  .eslintrc.js
  __tests__/components/App.test.js
  __tests__/components/Header.test.js
  __tests__/components/LoginPanel.test.js
  __tests__/components/NewsItem.test.js
  __tests__/components/NewsPanel.test.js
  __tests__/components/RootComponent.test.js
  __tests__/components/editor/Editor.test.js
  __tests__/components/editor/ImportResourceTemplate.test.js
  __tests__/components/editor/InputListLOC.test.js
  __tests__/components/editor/InputLiteral.test.js
  __tests__/components/editor/InputLookupQA.test.js
  __tests__/components/editor/OutlineHeader.test.js
  __tests__/components/editor/PropertyResourceTemplate.test.js
  __tests__/components/editor/SinopiaResourceTemplates.test.js
  __tests__/reducers/index.test.js
  package-lock.json
  package.json
  server.js
  src/components/LoginPanel.jsx
  src/components/editor/ImportResourceTemplate.jsx
  src/components/editor/InputListLOC.jsx
  src/components/editor/InputLookupQA.jsx
  src/components/editor/SinopiaResourceTemplates.jsx
  src/sinopiaServer.js
Labels: M3

#550 Prevent upload modal & flash message from showing stale messages
  .babelrc
  __tests__/components/editor/ImportResourceTemplate.test.js
  package-lock.json
  package.json
  src/components/editor/ImportResourceTemplate.jsx
  src/components/editor/SinopiaResourceTemplates.jsx
Labels: M3

#553 fix login on non-dev instances. other touchups.
  README.md
  package.json
  webpack.config.js
Labels: M3, bug, debt, needs review, tests

#552 Isolate Sinopia server operations to a single module
  .eslintrc.js
  __mocks__/SinopiaClientErrorFake.js
  __mocks__/SinopiaClientSuccessFake.js
  __mocks__/mockAWSData.js
  __tests__/Config.test.js
  __tests__/actions/index.test.js
  __tests__/components/RootComponent.test.js
  __tests__/components/editor/ImportResourceTemplate.test.js
  __tests__/components/editor/RequiredSuperscript.test.js
  __tests__/components/editor/SinopiaResourceTemplates.test.js
  __tests__/components/editor/UpdateResourceModal.test.js
  __tests__/reducers/authenticate.test.js
  __tests__/reducers/inputs.test.js
  __tests__/reducers/lang.test.js
  __tests__/reducers/lookups.test.js
  __tests__/sinopiaServer.test.js
  __tests__/sinopiaServerSpoof.test.js
  package.json
  src/CognitoUtils.js
  src/Config.js
  src/actions/index.js
  src/components/App.jsx
  src/components/LoginPanel.jsx
  src/components/NewsPanel.jsx
  src/components/RootContainer.jsx
  src/components/editor/ImportResourceTemplate.jsx
  src/components/editor/InputLiteral.jsx
  src/components/editor/RequiredSuperscript.jsx
  src/reducers/authenticate.js
  src/reducers/lang.js
  src/reducers/lookups.js
  src/sinopiaServer.js
  src/sinopiaServerSpoof.js
  src/store.js
Labels: M3, debt, editor-refactor

#557 Use react-bootstrap-table2 in favor of react-bootstrap-table
  __tests__/components/editor/SinopiaResourceTemplates.test.js
  package-lock.json
  package.json
  src/components/editor/SinopiaResourceTemplates.jsx
Labels: M3, debt

#559 Display messages for all resource templates in a profile
  __tests__/components/editor/ImportResourceTemplate.test.js
  __tests__/components/editor/SinopiaResourceTemplates.test.js
  __tests__/components/editor/UpdateResourceModal.test.js
  src/components/editor/ImportFileZone.jsx
  src/components/editor/ImportResourceTemplate.jsx
  src/components/editor/SinopiaResourceTemplates.jsx
  src/components/editor/UpdateResourceModal.jsx
Labels: M3

#558 InputLookupQA fixes and redux connection
  __tests__/components/editor/InputLookupQA.test.js
  src/components/editor/InputListLOC.jsx
  src/components/editor/InputLookupQA.jsx
  src/components/editor/PropertyComponent.jsx
Labels: BFF, M3

#570 Add unit tests for CognitoUtils class
  __tests__/CognitoUtils.test.js
  src/CognitoUtils.js
Labels: M3, debt, tests

#533 Support for repeatable when type is a Resource
  __tests__/Utilities.test.js
  __tests__/components/editor/PropertyActionButtons.test.js
  __tests__/components/editor/PropertyResourceTemplate.test.js
  __tests__/components/editor/PropertyTemplateOutline.test.js
  __tests__/components/editor/ResourceTemplateForm.test.js
  __tests__/integration/repeatableResources.test.js
  package-lock.json
  src/Utilities.js
  src/components/editor/PropertyActionButtons.jsx
  src/components/editor/PropertyComponent.jsx
  src/components/editor/PropertyResourceTemplate.jsx
  src/components/editor/PropertyTemplateOutline.jsx
  src/components/editor/ResourceProperty.jsx
  src/components/editor/ResourceTemplateForm.jsx
  src/reducers/index.js
  static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/MonographInstance.json
Labels: BFF, M3

#574 Extract and pass along property template defaults from InputLookupQA component to typeahead
  __tests__/Utilities.test.js
  __tests__/components/editor/InputListLOC.test.js
  __tests__/components/editor/InputLookupQA.test.js
  __tests__/components/editor/PropertyComponent.test.js
  src/Utilities.js
  src/components/editor/InputListLOC.jsx
  src/components/editor/InputLookupQA.jsx
  src/components/editor/PropertyComponent.jsx
Labels: M3

#580 Fix malformed URI in PropertyComponent test
  __tests__/components/editor/PropertyComponent.test.js
Labels: M3

#577 Add reduxPath to PropertyComponent
  __tests__/components/editor/PropertyComponent.test.js
  __tests__/components/editor/PropertyTemplateOutline.test.js
  package-lock.json
  package.json
  src/components/editor/PropertyComponent.jsx
  src/components/editor/ResourceTemplateForm.jsx
Labels: BFF, M3, bug

#582 Fix typo in copyright statement
  __tests__/integration/repeatableResources.test.js
Labels: M4

#587 Create a test for display of authentication errors
  __tests__/components/LoginPanel.test.js
  src/components/LoginPanel.jsx
Labels: M3, needs review

#585 Fix skipped app tests
  __tests__/CognitoUtils.test.js
  __tests__/components/App.test.js
Labels: M3, needs review

#586 Remove indirection
  __tests__/components/editor/Editor.test.js
  src/components/editor/Editor.jsx
  src/components/editor/ImportResourceTemplate.jsx
  src/sinopiaServer.js
Labels: M4, needs review

#588 Extract action creators and selectors so they can be tested.
  __tests__/actionCreators.test.js
  __tests__/authSelectors.test.js
  src/actionCreators.js
  src/authSelectors.js
  src/components/LoginPanel.jsx
  src/components/editor/Editor.jsx
  src/components/editor/ImportResourceTemplate.jsx
Labels: M3, needs review

#591 Fix Getty AAT QA lookups
  __tests__/components/editor/InputListLOC.test.js
  __tests__/components/editor/InputLookupQA.test.js
  src/components/editor/InputListLOC.jsx
  src/components/editor/InputLookupQA.jsx
  static/spoofedFilesFromServer/fromSinopiaServer/lookupConfig.json
Labels: M3

#571 Fix lookup config bug in InputListLOC
  __tests__/components/editor/InputListLOC.test.js
  __tests__/components/editor/InputLookupQA.test.js
  src/Utilities.js
  src/components/editor/InputListLOC.jsx
  src/components/editor/InputLiteral.jsx
  src/components/editor/InputLookupQA.jsx
  src/components/editor/PropertyComponent.jsx
  src/components/editor/PropertyTemplateOutline.jsx
Labels: M3

#567 Property template text remarks are tooltips on the property panel and the nested property outline
  __tests__/components/editor/OutlineHeader.test.js
  __tests__/components/editor/PropertyLabel.test.js
  __tests__/components/editor/PropertyPanel.test.js
  __tests__/components/editor/PropertyRemark.test.js
  __tests__/components/editor/PropertyTemplateOutline.test.js
  package-lock.json
  src/components/editor/InputListLOC.jsx
  src/components/editor/OutlineHeader.jsx
  src/components/editor/PropertyLabel.jsx
  src/components/editor/PropertyPanel.jsx
  src/components/editor/PropertyRemark.jsx
  src/components/editor/PropertyTemplateOutline.jsx
  src/styles/main.css
Labels: M3

#601 Update package-lock.json
  package-lock.json
Labels: M4

#592 589 handle subauthorities
  __tests__/Config.test.js
  __tests__/components/editor/InputLookupQA.test.js
  src/Config.js
  src/components/editor/InputLookupQA.jsx
  src/lib/apidoc.json
Labels: M4
