Repository LD4P/sinopia_editor, pull requests merged in 2019-04, with the labels that each got.

#439 Multiplelookups 348
  __tests__/components/editor/InputLookupQA.test.js
  package-lock.json
  src/components/editor/InputLookupQA.jsx
  src/components/editor/ResourceTemplateForm.jsx
  src/styles/main.css
  static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/MonographInstance.json
Labels: needs review

#443 Resourcelabel 393
  __tests__/components/editor/Editor.test.js
  __tests__/components/editor/ResourceTemplate.test.js
  src/components/editor/Editor.jsx
  src/components/editor/ResourceTemplate.jsx
Labels: needs review

#446 sending multiple lookup config items array to input qa
  __tests__/components/editor/PropertyTemplateOutline.test.js
  src/components/editor/PropertyTemplateOutline.jsx
Labels: needs review

#440 Conditional Redux plugin support depending on Environment
  src/store.js
Labels: needs review

#447 Update schema version info message when importing a new RT/profile
  __tests__/integration/schemaValidation.test.js
  src/Config.js
  src/components/editor/ImportFileZone.jsx
Labels: needs review

#449 Create containers and ACLs in Trellis when spinning up docker-compose
  README.md
  docker-compose.yml
Labels: needs review

#441 Embedded resource template Redux support for UI
  .eslintrc.js
  __tests__/actions/index.test.js
  __tests__/components/editor/InputLiteral.test.js
  __tests__/components/editor/PropertyResourceTemplate.test.js
  __tests__/components/editor/PropertyTemplateOutline.test.js
  __tests__/reducers/index.test.js
  __tests__/reducers/literal.test.js
  src/actions/index.js
  src/components/editor/InputLiteral.jsx
  src/components/editor/PropertyPanel.jsx
  src/components/editor/PropertyResourceTemplate.jsx
  src/components/editor/PropertyTemplateOutline.jsx
  src/components/editor/PropertyTypeRow.jsx
  src/components/editor/ResourceTemplateForm.jsx
  src/reducers/index.js
  src/reducers/literal.js
  src/styles/main.css
Labels: needs review

#453 Editor fetches profiles with resource templates from sinopia server
  .eslintrc.js
  README.md
  __tests__/Config.test.js
  __tests__/components/DescPanel.test.js
  __tests__/components/HomePage.test.js
  __tests__/components/editor/Editor.test.js
  __tests__/components/editor/ImportFileZone.test.js
  __tests__/components/editor/ImportResourceTemplate.test.js
  __tests__/components/editor/InputLang.test.js
  __tests__/components/editor/PropertyPanel.test.js
  __tests__/components/editor/PropertyTemplateOutline.test.js
  __tests__/components/editor/ResourceTemplate.test.js
  __tests__/components/editor/ResourceTemplateForm.test.js
  __tests__/components/editor/SinopiaResourceTemplates.test.js
  __tests__/integration/schemaValidation.test.js
  __tests__/reducers/index.test.js
  package.json
  src/Config.js
  src/Logout.js
  src/components/HomePage.jsx
  src/components/editor/Editor.jsx
  src/components/editor/ImportFileZone.jsx
  src/components/editor/ImportResourceTemplate.jsx
  src/components/editor/InputLang.jsx
  src/components/editor/PropertyTemplateOutline.jsx
  src/components/editor/ResourceTemplate.jsx
  src/components/editor/ResourceTemplateForm.jsx
  src/components/editor/SinopiaResourceTemplates.jsx
  src/reducers/index.js
  src/sinopiaServer.js
Labels: needs review

#462 Update config with new trellis base url
  __tests__/Config.test.js
  src/Config.js
Labels: needs review

#461 Update resources and warn users
  __tests__/components/editor/ImportResourceTemplate.test.js
  __tests__/components/editor/SinopiaResourceTemplates.test.js
  __tests__/components/editor/UpdateResourceModal.test.js
  src/components/Login.jsx
  src/components/editor/ImportResourceTemplate.jsx
  src/components/editor/SinopiaResourceTemplates.jsx
  src/components/editor/UpdateResourceModal.jsx
Labels: needs review

#469 Update npm packages
  .eslintrc-todo.yml
  .eslintrc.yml
  package-lock.json
  package.json
Labels: needs review

#470 Use 0.2 tag of ACL docker image
  docker-compose.yml
Labels: needs review

#472 Tiny test tweaks (no code changed)
  __tests__/components/App.test.js
  __tests__/components/editor/Header.test.js
Labels: needs review

#471 Test spaceless ids (refactor the schema validation tests)
  __tests__/Config.test.js
  __tests__/__fixtures__/lcc_v0.0.9.json
  __tests__/__fixtures__/lcc_v0.1.0_bad_id.json
  __tests__/__fixtures__/place_profile_v0.0.9.json
  __tests__/components/RootComponent.test.js
  __tests__/components/editor/ImportFileZone.test.js
  __tests__/components/editor/ImportResourceTemplate.test.js
  __tests__/integration/schemaValidation.test.js
  package-lock.json
  src/Config.js
  src/components/editor/ImportFileZone.jsx
Labels: needs review

#466 Allow environment variable injection from containerland into application
  .dockerignore
  Dockerfile
  README.md
  __tests__/Config.test.js
  __tests__/components/App.test.js
  __tests__/components/editor/PropertyTemplateOutline.test.js
  __tests__/components/editor/ResourceTemplate.test.js
  __tests__/reducers/linkedData.test.js
  __tests__/sinopiaServer.test.js
  docker-compose.yml
  package-lock.json
  package.json
  src/Config.js
  src/components/editor/PropertyTemplateOutline.jsx
  src/components/editor/ResourceTemplate.jsx
  src/components/editor/ResourceTemplateForm.jsx
  src/reducers/linkedData.js
  src/sinopiaServer.js
  webpack.config.js
Labels: M3, needs review

#475 Pass Cognito credentials to the platformdata service via env variables
  .gitignore
  README.md
  docker-compose.yml
Labels: M3, needs review

#477 Use CircleCI to build env-specific docker images
  .circleci/config.yml
  .dockerignore
  Dockerfile
Labels: M3, needs review

#478 Build stage and prod images in CI
  .circleci/config.yml
Labels: M3, needs review, ops

#483 Fix typo in CI configuration that broke build
  .circleci/config.yml
Labels: M3, bug, needs review

#484 Fixes header and login links
  __tests__/Config.test.js
  __tests__/components/Header.test.js
  src/Config.js
  src/components/Header.jsx
  src/components/editor/Header.jsx
Labels: needs review

#486 Replaces the /import path name with the path name /templates
  __tests__/components/App.test.js
  __tests__/components/Header.test.js
  __tests__/components/Login.test.js
  __tests__/components/editor/Header.test.js
  __tests__/integration/schemaValidation.test.js
  src/components/App.jsx
  src/components/Header.jsx
  src/components/Login.jsx
  src/components/editor/Header.jsx
Labels: needs review

#487 Fix AWS Cognito Domain to remove extra https in login link
  __tests__/Config.test.js
  src/Config.js
Labels: needs review

#482 Preview modal
  README.md
  __tests__/components/editor/Editor.test.js
  __tests__/components/editor/RDFModal.test.js
  src/components/editor/Editor.jsx
  src/components/editor/RDFModal.jsx
  src/reducers/index.js
Labels: needs review

#489 Support in Editor for Server Spoofing
  __tests__/Config.test.js
  __tests__/components/editor/ResourceTemplateForm.test.js
  __tests__/reducers/index.test.js
  __tests__/reducers/linkedData.test.js
  __tests__/sinopiaServer.test.js
  src/components/editor/ResourceTemplateForm.jsx
  src/reducers/index.js
  src/reducers/linkedData.js
  src/sinopiaServer.js
Labels: needs review

#488 Fetch Help and Resources menu items from github pages
  __tests__/Config.test.js
  __tests__/components/CanvasMenu.test.js
  __tests__/integration/landingPage.test.js
  src/Config.js
  src/components/App.jsx
  src/components/CanvasMenu.jsx
Labels: needs review
