Repository LD4P/sinopia_editor, pull requests merged in 2019-07, with the labels that each got.

#860 Omits blank nodes when items arrays are empty.
  __tests__/GraphBuilder.test.js
  src/GraphBuilder.js
Labels: needs review

#862 Adds ability to download resource templates.
  __tests__/components/templates/Download.test.js
  __tests__/components/templates/SinopiaResourceTemplates.test.js
  package-lock.json
  package.json
  src/components/templates/Download.jsx
  src/components/templates/SinopiaResourceTemplates.jsx
  src/styles/main.css
Labels: needs review

#864 Avoid rendering into the state
  __tests__/components/editor/property/PropertyTemplateOutline.test.js
  src/components/editor/property/PropertyTemplateOutline.jsx
Labels: BFF, M4

#870 Convert RequiredSuperscript to a functional component
  src/components/editor/property/RequiredSuperscript.jsx
Labels: M4

#869 Convert PropertyLabel to a functional component
  src/components/editor/property/PropertyLabel.jsx
Labels: M4

#875 Make the PropertyPanel a functional component
  src/components/editor/property/PropertyPanel.jsx
Labels: BFF, M4

#877 All the properties should be on the same resource
  src/components/editor/property/PropertyResourceTemplate.jsx
Labels: BFF

#876 Refactor PropertyTemplateOutline
  src/components/editor/property/PropertyTemplateOutline.jsx
Labels: BFF, M4

#878 Remove defaults on template that has valueTemplateRefs
  __tests__/__fixtures__/MonographInstance.json
Labels: BFF, M4

#868 Proxy ElasticSearch service
  .circleci/config.yml
  Dockerfile
  __tests__/Config.test.js
  package-lock.json
  package.json
  server.js
  src/Config.js
  webpack.config.js
Labels: M4

#880 Transform PropertyTemplateOutline into a basic connected component
  __tests__/components/editor/property/PropertyResourceTemplate.test.js
  __tests__/components/editor/property/PropertyTemplateOutline.test.js
  src/components/editor/property/PropertyTemplateOutline.jsx
Labels: M4

#865 Removes property template as InputLiteral prop. Validates resource te…
  __tests__/ResourceTemplateValidator.test.js
  __tests__/integration/repeatedPropertyURI.test.js
  __tests__/reducers/index.test.js
  src/ResourceTemplateValidator.js
  src/actionCreators.js
  src/actions/index.js
  src/components/editor/ResourceTemplate.jsx
  src/components/editor/property/InputLiteral.jsx
  src/components/editor/property/PropertyComponent.jsx
  src/reducers/index.js
Labels: needs review

#887 Add comments to Express server
  server.js
Labels: M4

#890 InputListLOC: changes redux state once again
  src/components/editor/property/InputListLOC.jsx
Labels: M4

#859 882 show version
  __tests__/components/App.test.js
  __tests__/components/Header.test.js
  src/actions/index.js
  src/components/App.jsx
  src/components/Header.jsx
  src/reducers/index.js
  src/store.js
  src/styles/main.css
Labels: M4

#892 Minor updates to keep version consistent on homepage and corrects a m…
  __tests__/components/Header.test.js
  src/components/home/NewsItem.jsx
Labels: BFF, M4

#872 Creates resource state builder, for transforming RDF to resource state.
  __tests__/ResourceStateBuilder.test.js
  package-lock.json
  package.json
  src/ResourceStateBuilder.js
  src/Utilities.js
Labels: M4

#899 Extract the model from the view logic
  __tests__/components/editor/property/ResourceProperty.test.js
  __tests__/integration/nestedResources.test.js
  src/components/editor/property/ResourceProperty.jsx
Labels: BFF, M4

#808 Load resources from Trellis
  __tests__/actionCreators.test.js
  __tests__/components/browse/Browse.test.js
  src/actionCreators.js
  src/actions/index.js
  src/components/browse/Browse.jsx
  src/reducers/index.js
  src/sinopiaServer.js
Labels: BFF, M4

#852 npm update eslint-plugin-react
  package-lock.json
  package.json
  src/components/App.jsx
  src/components/editor/property/InputListLOC.jsx
  src/components/editor/property/InputLookupQA.jsx
Labels: needs review, question

#903 dependency updates
  package-lock.json
  package.json
Labels: needs review

#906 simplify findNode conditional logic
  src/selectors/resourceSelectors.js
Labels: debt, needs review

#909 NewsItem: get the version number from package.json
  __tests__/components/home/NewsItem.test.js
  src/components/home/NewsItem.jsx
Labels: debt, enhancement, needs review

#926 Revert #924 - add index_url to build args
  docker-compose.yml
Labels: M4

#936 Fixes prop type error for InputListLOC and InputLookupQA.
  src/components/editor/property/InputListLOC.jsx
  src/components/editor/property/InputLookupQA.jsx
Labels: BFF

#935 Prevents naving to editor when no resource.
  __tests__/components/App.test.js
  __tests__/components/Header.test.js
  src/components/App.jsx
  src/components/Header.jsx
Labels: BFF, M4

#939 Add validation to prevent property templates with defaults and refere…
  __tests__/ResourceTemplateValidator.test.js
  __tests__/__fixtures__/defaultsAndRefs.json
  __tests__/fixtureLoaderHelper.js
  src/ResourceTemplateValidator.js
Labels: BFF

#941 Show all authoratative labels
  __tests__/components/editor/property/InputListLOC.test.js
  src/components/editor/property/InputListLOC.jsx
Labels: BFF, M4

#954 Make the error messages easier to read and understand
  __tests__/integration/schemaValidation.test.js
  src/components/templates/ImportFileZone.jsx
Labels: BFF, M4

#953 Remove button
  __tests__/components/editor/ResourceTemplateForm.test.js
  __tests__/components/editor/property/PropertyActionButtons.test.js
  __tests__/components/editor/property/PropertyResourceTemplate.test.js
  __tests__/components/editor/property/ResourceProperty.test.js
  __tests__/integration/addRemoveButtons.test.js
  __tests__/integration/integrationHelper.js
  __tests__/reducers/index.test.js
  package.json
  src/actions/index.js
  src/components/editor/ResourceTemplateForm.jsx
  src/components/editor/property/PropertyActionButtons.jsx
  src/components/editor/property/PropertyResourceTemplate.jsx
  src/components/editor/property/PropertyTemplateOutline.jsx
  src/components/editor/property/ResourceProperty.jsx
  src/reducers/index.js
Labels: BFF, M4

#960 Security update of Lodash
  package-lock.json
  package.json
Labels: BFF, M4

#962 Allows blank defaultURIs for literals.
  __tests__/ResourceTemplateValidator.test.js
  __tests__/__fixtures__/literalDefaultURI.json
  __tests__/fixtureLoaderHelper.js
  src/ResourceTemplateValidator.js
Labels: BFF, needs review

#963 Splits actionCreators into multiple files.
  __tests__/actionCreators/authenticate.test.js
  __tests__/actionCreators/resourceTemplates.test.js
  __tests__/actionCreators/resources.test.js
  src/actionCreators/authenticate.js
  src/actionCreators/resourceTemplates.js
  src/actionCreators/resources.js
  src/components/LoginPanel.jsx
  src/components/browse/Browse.jsx
  src/components/editor/Editor.jsx
  src/components/editor/ResourceTemplate.jsx
  src/components/editor/property/PropertyActionButtons.jsx
  src/components/editor/property/PropertyTemplateOutline.jsx
  src/components/load/ImportResource.jsx
  src/components/templates/SinopiaResourceTemplates.jsx
Labels: BFF, needs review

#965 Clears resource templates when loading resource.
  __tests__/actionCreators/resources.test.js
  __tests__/reducers/index.test.js
  src/actionCreators/resources.js
  src/actions/index.js
  src/reducers/index.js
Labels: BFF, needs review

#964 Extract the PropertyTemplate shape to a module
  __tests__/components/editor/ResourceTemplateForm.test.js
  __tests__/components/editor/property/PropertyComponent.test.js
  src/SinopiaPropTypes.js
  src/components/editor/property/InputListLOC.jsx
  src/components/editor/property/InputLiteral.jsx
  src/components/editor/property/InputLookupQA.jsx
  src/components/editor/property/InputURI.jsx
  src/components/editor/property/PropertyComponent.jsx
Labels: BFF, M4

#951 Sinopia element
  __tests__/__fixtures__/SinopiaLookup.json
  __tests__/components/editor/property/InputLookupSinopia.test.js
  __tests__/components/editor/property/PropertyComponent.test.js
  __tests__/fixtureLoaderHelper.js
  src/Config.js
  src/Utilities.js
  src/components/editor/property/InputLookupSinopia.jsx
  src/components/editor/property/PropertyComponent.jsx
  src/reducers/inputs.js
  static/lookupConfig.json
Labels: BFF, M4

#970 Fix bad tests
  __tests__/components/editor/property/InputListLOC.test.js
  __tests__/components/editor/property/InputLiteral.test.js
  __tests__/components/editor/property/InputLookupQA.test.js
  __tests__/components/editor/property/InputURI.test.js
Labels: debt

#959 Adds add and remove buttons for toggling properties.
  __tests__/components/editor/property/OutlineHeader.test.js
  __tests__/components/editor/property/PropertyTemplateOutline.test.js
  __tests__/integration/addRemoveButtons.test.js
  __tests__/integration/nestedResources.test.js
  __tests__/integration/previewRDFHelper.js
  __tests__/integration/repeatableResources.test.js
  __tests__/reducers/index.test.js
  src/components/editor/property/OutlineHeader.jsx
  src/components/editor/property/PropertyActionButtons.jsx
  src/components/editor/property/PropertyTemplateOutline.jsx
  src/reducers/index.js
Labels: BFF, M4, needs review

#975 Moves resource template summaries to redux state and loading to a thunk.
  __tests__/actionCreators/resourceTemplates.test.js
  __tests__/components/App.test.js
  __tests__/components/templates/Download.test.js
  __tests__/components/templates/ImportResourceTemplate.test.js
  __tests__/components/templates/SinopiaResourceTemplates.test.js
  src/actionCreators/resourceTemplates.js
  src/actionCreators/resources.js
  src/actions/index.js
  src/components/App.jsx
  src/components/templates/Download.jsx
  src/components/templates/ImportResourceTemplate.jsx
  src/components/templates/SinopiaResourceTemplates.jsx
  src/reducers/index.js
  src/store.js
Labels: BFF, M4

#978 Sets correct container when saving rdf.
  __tests__/components/editor/GroupChoiceModal.test.js
  src/components/editor/GroupChoiceModal.jsx
Labels: BFF, needs review

#982 Adds Tagged Release Checklist Github Issue Template
  .github/ISSUE_TEMPLATE/tagged-release.md
  README.md
Labels: BFF

#988 Upgrade to node 12.6
  .circleci/config.yml
  Dockerfile
  package.json
Labels: BFF

#994 Fixes loading of existing resources.
  __tests__/ResourceStateBuilder.test.js
  src/ResourceStateBuilder.js
  src/Utilities.js
Labels: BFF

#996 Remove unused code
  __tests__/reducers/inputs.test.js
  src/actions/index.js
  src/components/editor/ResourceTemplateForm.jsx
  src/reducers/index.js
  src/reducers/inputs.js
Labels: debt

#987 Clear errors when loading a resource template
  __tests__/reducers/index.test.js
  src/reducers/index.js
Labels: BFF

#984 Loading an existing resource sets the resource URI
  __tests__/actionCreators/resources.test.js
  src/actionCreators/resources.js
Labels: BFF

#998 mapStateToProps does not need to return reduxPath, it's a passed in prop
  src/components/editor/property/InputLiteral.jsx
  src/components/editor/property/InputURI.jsx
Labels: debt

#997 Remove unnecessary properties
  __tests__/components/editor/property/PropertyLabel.test.js
  __tests__/components/editor/property/PropertyPanel.test.js
  src/components/editor/ResourceTemplateForm.jsx
  src/components/editor/property/OutlineHeader.jsx
  src/components/editor/property/PropertyLabel.jsx
  src/components/editor/property/PropertyPanel.jsx
Labels: debt

#999 Rename actions to better describe the action the user took
  __tests__/actions/index.test.js
  __tests__/reducers/inputs.test.js
  src/actions/index.js
  src/components/editor/property/InputLiteral.jsx
  src/components/editor/property/InputURI.jsx
  src/reducers/index.js
  src/reducers/inputs.js
Labels: debt, editor-refactor

#1000 Passing uri to setItems is unnecessary
  __tests__/components/editor/property/InputLiteral.test.js
  __tests__/components/editor/property/InputURI.test.js
  src/components/editor/property/InputLiteral.jsx
  src/components/editor/property/InputURI.jsx
Labels: debt

#1002 Provide a sensible default for Config.searchHost
  Dockerfile
  src/Config.js
Labels: BFF

#1004 Links tokens in InputLookupQA component.
  __tests__/components/editor/property/InputLookupQA.test.js
  src/components/editor/property/InputLookupQA.jsx
Labels: BFF

#976 Add search tab to editor
  __tests__/components/App.test.js
  __tests__/components/Header.test.js
  __tests__/components/browse/Browse.test.js
  __tests__/components/search/Search.test.js
  __tests__/components/search/SearchResults.test.js
  src/actions/index.js
  src/components/App.jsx
  src/components/Header.jsx
  src/components/browse/Browse.jsx
  src/components/search/Search.jsx
  src/components/search/SearchResults.jsx
  src/reducers/index.js
  src/reducers/inputs.js
  src/store.js
Labels: BFF, M4

#1005 Simplify the representation of a language tag
  __tests__/GraphBuilder.test.js
  __tests__/actionCreators/resources.test.js
  __tests__/components/editor/property/InputLang.test.js
  __tests__/components/editor/property/InputLiteral.test.js
  src/GraphBuilder.js
  src/Utilities.js
  src/components/editor/property/InputLang.jsx
  src/components/editor/property/InputLiteral.jsx
  src/reducers/inputs.js
Labels: debt

#1011 Extract the reducers related to entities to a separate file
  __tests__/reducers/entities.test.js
  __tests__/reducers/index.test.js
  src/reducers/entities.js
  src/reducers/index.js
Labels: BFF, M4

#1003 Extract LanguageButton from InputLiteral
  __tests__/components/editor/property/InputLiteral.test.js
  __tests__/components/editor/property/LanguageButton.test.js
  src/components/editor/property/InputLiteral.jsx
  src/components/editor/property/LanguageButton.jsx
Labels: BFF, M4

#1012 Load the language data once into entities
  __tests__/components/editor/property/InputLang.test.js
  __tests__/reducers/entities.test.js
  src/actionCreators/languages.js
  src/actions/entities.js
  src/actions/index.js
  src/components/editor/property/InputLang.jsx
  src/components/editor/property/LanguageButton.jsx
  src/reducers/entities.js
  src/reducers/index.js
Labels: BFF

#1019 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: BFF, enhancement

#1017 Update ResourceStateBuilder to build the simpler language
  __tests__/ResourceStateBuilder.test.js
  src/ResourceStateBuilder.js
Labels: BFF, bug

#995 Adds option for new uri to InputLookupQA.
  __tests__/components/editor/property/InputLookupQA.test.js
  src/Utilities.js
  src/components/editor/property/InputLookupQA.jsx
  src/components/editor/property/InputURI.jsx
Labels: BFF, M4

#1028 Correctly handles nested properties that are mandatory and have defau…
  __tests__/actionCreators/resources.test.js
  src/actionCreators/resources.js
Labels: BFF

#1026 Switch to using shortid for lang id to avoid blank or missing default…
  __tests__/Utilities.test.js
  __tests__/actionCreators/resources.test.js
  src/Utilities.js
Labels: BFF, needs review

#1021 Adds recursive validation. Fixes display of validation errors.
  __tests__/ResourceValidator.test.js
  __tests__/Validator.test.js
  __tests__/components/editor/property/InputListLOC.test.js
  __tests__/components/editor/property/InputLiteral.test.js
  __tests__/components/editor/property/InputLookupQA.test.js
  __tests__/components/editor/property/InputLookupSinopia.test.js
  __tests__/components/editor/property/OutlineHeader.test.js
  __tests__/integration/previewRDFHelper.js
  __tests__/reducers/inputs.test.js
  src/ResourceValidator.js
  src/Validator.js
  src/components/editor/ErrorMessages.jsx
  src/components/editor/property/InputListLOC.jsx
  src/components/editor/property/InputLiteral.jsx
  src/components/editor/property/InputLookupQA.jsx
  src/components/editor/property/InputLookupSinopia.jsx
  src/components/editor/property/OutlineHeader.jsx
  src/reducers/inputs.js
  src/selectors/resourceSelectors.js
  src/store.js
Labels: BFF

#1041 Patch Release 0.3.5
  package-lock.json
  package.json
  src/components/home/NewsItem.jsx
Labels: BFF, M4

#1050 Adds error message when user enters a literal in InputURI.
  __tests__/components/editor/property/InputURI.test.js
  src/components/editor/property/InputURI.jsx
Labels: BFF

#1052 Adds notification when saving and publishing a resource.
  __tests__/components/editor/GroupChoiceModal.test.js
  __tests__/components/editor/SaveAlert.test.js
  __tests__/reducers/index.test.js
  src/components/editor/GroupChoiceModal.jsx
  src/components/editor/ResourceTemplate.jsx
  src/components/editor/SaveAlert.jsx
  src/reducers/index.js
Labels: BFF

#1054 Also validates when adding / removing properties.
  __tests__/integration/correctRdfInPreview/literalPropertyTemplates.test.js
  __tests__/reducers/index.test.js
  src/reducers/index.js
Labels: BFF

#1057 Allows literal in InputLookupQA.
  __tests__/components/editor/property/InputLookupQA.test.js
  __tests__/integration/previewRDFHelper.js
  src/components/editor/property/InputLookupQA.jsx
Labels: BFF

#1076 Changes add buttons to add another.
  __tests__/components/editor/property/PropertyActionButtons.test.js
  __tests__/integration/addRemoveButtons.test.js
  __tests__/integration/repeatableResources.test.js
  src/components/editor/property/PropertyActionButtons.jsx
  src/components/editor/property/PropertyResourceTemplate.jsx
  src/components/editor/property/ResourceProperty.jsx
Labels: BFF

#1077 Removed duplicate lookups
  static/lookupConfig.json
Labels: BFF

#1080 Changes to adding / toggling of properties.
  __tests__/components/editor/property/OutlineHeader.test.js
  src/components/editor/property/OutlineHeader.jsx
  src/styles/main.css
Labels: BFF

#1081 Use the Button attributes rather than class
  __tests__/components/editor/GroupChoiceModal.test.js
  src/components/editor/GroupChoiceModal.jsx
  src/components/editor/SaveAndPublishButton.jsx
Labels: BFF

#1086 Switches to a right chevron for contracted toggle.
  __tests__/components/editor/property/OutlineHeader.test.js
  src/components/editor/property/OutlineHeader.jsx
Labels: BFF

#1087 Added + before blue Add button on property panel.
  __tests__/integration/nestedResources.test.js
  src/components/editor/property/PropertyPanel.jsx
Labels: BFF

#1088 Only render property panel body when it has been added.
  __tests__/components/editor/property/PropertyPanel.test.js
  src/components/editor/property/PropertyPanel.jsx
Labels: BFF

#1085 Aligned InputLiteral and InputLookup.
  __tests__/components/editor/property/InputLiteral.test.js
  src/components/editor/property/InputLiteral.jsx
  src/components/editor/property/LanguageButton.jsx
  src/styles/main.css
Labels: BFF

#1090 make "required" asterisk same color as text
  __tests__/components/editor/property/RequiredSuperscript.test.js
  src/components/editor/property/RequiredSuperscript.jsx
Labels: BFF, M4

#1093 Fixes PropType for current user for SaveAndPublishButton.
  __tests__/components/editor/SaveAndPublishButton.test.js
  src/components/editor/SaveAndPublishButton.jsx
Labels: BFF

#1095 Patch 0.3.8
  .github/ISSUE_TEMPLATE/tagged-release.md
  package-lock.json
  package.json
Labels: BFF, M4

#1097 Remove unnecessary property formData from InputLiteral
  __tests__/components/editor/property/InputLiteral.test.js
  src/components/editor/property/InputLiteral.jsx
Labels: BFF

#1094 Simplify LanguageButton
  src/components/editor/property/LanguageButton.jsx
Labels: BFF

#1096 Remove language label from the resource state
  __tests__/GraphBuilder.test.js
  __tests__/actionCreators/resources.test.js
  __tests__/components/editor/property/InputLiteral.test.js
  __tests__/selectors/resourceSelectors.test.js
  src/GraphBuilder.js
  src/Utilities.js
  src/components/editor/property/InputLang.jsx
  src/components/editor/property/InputLiteral.jsx
  src/components/editor/property/LanguageButton.jsx
Labels: BFF

#1098 Make the layout responsive.
  src/components/editor/ResourceTemplate.jsx
  src/components/editor/ResourceTemplateForm.jsx
  src/components/editor/property/PropertyPanel.jsx
  src/styles/main.css
Labels: BFF

#1102 Right align the add/remove panel header buttons
  src/styles/main.css
Labels: BFF, M4, bug

#1103 Resource builder should set the language correctly
  __tests__/ResourceStateBuilder.test.js
  src/ResourceStateBuilder.js
Labels: BFF, bug

#1105 Don't break across a panel when there is only one
  src/styles/main.css
Labels: BFF

#1106 Only the buttons in the header should align right
  src/styles/main.css
Labels: BFF

#1107 "Add another" button for property is hidden rather than disabled
  __tests__/components/editor/property/PropertyActionButtons.test.js
  __tests__/components/editor/property/PropertyResourceTemplate.test.js
  __tests__/components/editor/property/PropertyTemplateOutline.test.js
  __tests__/components/editor/property/ResourceProperty.test.js
  src/components/editor/property/PropertyActionButtons.jsx
  src/components/editor/property/PropertyResourceTemplate.jsx
  src/components/editor/property/PropertyTemplateOutline.jsx
  src/components/editor/property/ResourceProperty.jsx
Labels: BFF, M4

#1091 Moves property info to icon. Bolds property labels.
  __tests__/components/editor/property/OutlineHeader.test.js
  __tests__/components/editor/property/PropertyLabel.test.js
  __tests__/components/editor/property/PropertyLabelInfo.test.js
  __tests__/components/editor/property/PropertyLabelInfoLink.test.js
  __tests__/components/editor/property/PropertyLabelInfoTooltip.test.js
  __tests__/components/editor/property/PropertyPanel.test.js
  __tests__/components/editor/property/RequiredSuperscript.test.js
  __tests__/integration/previewRDFHelper.js
  src/components/editor/property/OutlineHeader.jsx
  src/components/editor/property/PropertyLabel.jsx
  src/components/editor/property/PropertyLabelInfo.jsx
  src/components/editor/property/PropertyLabelInfoLink.jsx
  src/components/editor/property/PropertyLabelInfoTooltip.jsx
  src/components/editor/property/PropertyPanel.jsx
  src/components/editor/property/RequiredSuperscript.jsx
  src/styles/main.css
Labels: BFF, M4

#1109 Adds loading by URI.
  __tests__/components/load/LoadByRDFForm.test.js
  __tests__/components/load/LoadByURIForm.test.js
  __tests__/components/load/LoadResource.test.js
  __tests__/integration/leaveEditor.test.js
  __tests__/integration/loadRDF.test.js
  src/components/App.jsx
  src/components/load/ImportResource.jsx
  src/components/load/LoadByRDFForm.jsx
  src/components/load/LoadByURIForm.jsx
  src/components/load/LoadResource.jsx
  src/selectors/resourceSelectors.js
Labels: BFF

#1108 Convert items to a hash instead of an array
  __tests__/GraphBuilder.test.js
  __tests__/ResourceStateBuilder.test.js
  __tests__/Utilities.test.js
  __tests__/actionCreators/resources.test.js
  __tests__/components/editor/property/InputLang.test.js
  __tests__/components/editor/property/InputLiteral.test.js
  __tests__/components/editor/property/LanguageButton.test.js
  __tests__/reducers/inputs.test.js
  src/GraphBuilder.js
  src/ResourceStateBuilder.js
  src/Utilities.js
  src/components/editor/property/InputLang.jsx
  src/components/editor/property/InputListLOC.jsx
  src/components/editor/property/InputLiteral.jsx
  src/components/editor/property/InputLookupQA.jsx
  src/components/editor/property/LanguageButton.jsx
  src/reducers/inputs.js
Labels: BFF, M4

#1110 Make InputLang a functional component
  __tests__/components/editor/property/InputLang.test.js
  src/components/editor/property/InputLang.jsx
Labels: BFF
